const AppConstant = {
  RECAPTCHA_SITE_KEY: '6LcCEZUgAAAAAHfQIJzV0kp1OZiti6ANfePnUbOb',

  video: {
    ENTRY_PAGE_SIZE: 48,
    EPISODE_PAGE_SIZE: 10,
    
    SETTING_SUBTITLE_DEFAULT_FONT_SIZE: '18',
    SETTING_SUBTITLE_FONT_SIZE: 'SETTING_SUBTITLE_FONT_SIZE',
  }
}

export default AppConstant;
